### ISSUE TITLE
Y'all got any more of that project access?

### ISSUE THREAD

**Issue by ReynoldsCahoon** [InfiniteEchoDev/TownOne2023Team5#1]
![image](https://github.com/InfiniteEchoDev/TownOne2023Team5/assets/2556251/32a65ea2-176c-4a37-b665-371949cd1caf)

Hook me up.

**Comment by InfiniteEchoDev** [comment]
![coming-right-up](https://github.com/InfiniteEchoDev/TownOne2023Team5/assets/79585979/91a2d84d-9552-45db-95a6-7b3d50684c33)

**Comment by ReynoldsCahoon** [comment]
Resolved!
